version: '3'
services:
  nodejs:
    # image: nodejs
    build: 
      context: .
      dockerfile: ./docker/node/dockerfile
    volumes:
     - ./nodeapp/app.js:/home/node/app/app.js
     - ./views:/home/node/app/views
    ports:
     - "80:8080"
