version: '3'
services:
  nodejs:
    # image: nodejs
    build: 
      context: .
      dockerfile: ./docker/node/dockerfile
    # volumes:
    #  - .:/app
    #  - /app/vendor
    #  - /app/bin
    ports:
     - "80:8080"
