FROM node:13-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY nodeapp/package*.json ./

RUN npm install nodemon -g

USER node
RUN npm install

EXPOSE 8080

CMD [ "nodemon", "app.js" ]