FROM node:13-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY nodeapp/package*.json ./

USER node
RUN npm install

COPY --chown=node:node nodeapp/app.js app.js
COPY --chown=node:node views/ views/

EXPOSE 8080

CMD [ "node", "app.js" ]